name: Build and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'maven'
          java-version: '3.8'

      - name: Build with Maven
        run: mvn package -Dflink.version=1.15.3 -Dflink.version.minor=1.8

      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Artifact to S3
        run: aws s3 cp target/basic-beam-app-1.0.jar s3://splore-data-stage-datalake-t0/test/beam_demo/basic-beam-app-1.0.jar
